SELECT SUM(SCORE) AS SCORE, E.EMP_NO, E.EMP_NAME, E.POSITION, E.EMAIL
FROM HR_EMPLOYEES AS E JOIN HR_GRADE AS G
ON E.EMP_NO = G.EMP_NO
WHERE G.YEAR = '2022'
GROUP BY G.EMP_NO
ORDER BY SUM(SCORE) DESC
LIMIT 1;
