SELECT CASE WHEN SUBSTR(DIFFERENTIATION_DATE, 6, 2) IN ('01', '02', '03') THEN '1Q'
        WHEN SUBSTR(DIFFERENTIATION_DATE, 6, 2) IN ('04', '05', '06') THEN '2Q'
        WHEN SUBSTR(DIFFERENTIATION_DATE, 6, 2) IN ('07', '08', '09') THEN '3Q'
        ELSE '4Q'
        END AS QUARTER,
        COUNT(*) AS ECOLI_COUNT
FROM ECOLI_DATA
GROUP BY QUARTER
ORDER BY QUARTER;
